# Generated by Django 4.2.23 on 2025-06-23 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='bio',
            field=models.TextField(blank=True, default='Hey there! I am using Django.'),
        ),
    ]
