# Generated by Django 4.2.23 on 2025-06-23 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_appuser_otp_alter_appuser_bio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appuser',
            name='phone_number',
        ),
    ]
